### ISSUE TITLE
Auto refresh on chrome when i presh ctr + s

### ISSUE THREAD

**Issue by ghost** [leijou/php-server#14]
Hello very nice pacage can you pls make auto refresh on chrome when i presh ctr + s

**Comment by FabioAmorim1501** [comment]
@George35mk , I use the [livereload](https://atom.io/packages/livereload) package with the extension for chrome/firefox along with this and it works like a charm!

**Comment by leijou** [comment]
Agreed, this is the job for another plugin. Thanks @FabioAmorim1501
