### ISSUE TITLE
Where is the used php installed?

### ISSUE THREAD

**Issue by janstieler** [leijou/php-server#18]
Hi,
does this server use the preinstalled PHP on OSX or where is the php installed for this server?
My Question comes why I have updated the PHP to PHP7 but if I load a phpinfo(); i get the info that the server is using PHP 5.5.38.

Kind regards

**Comment by leijou** [comment]
By default just the command `php` will be run. You can change this and use a specific php binary (say, `/usr/share/sbin/php7`) in the "Path to PHP Executable" setting of the package
