### ISSUE TITLE
default port change

### ISSUE THREAD

**Issue by aurelio125** [leijou/php-server#27]
![chrome](https://user-images.githubusercontent.com/36461382/36181095-8a9d3804-1123-11e8-90bd-5ed5613f5c1d.jpg)
Hello,
I have a problem,
set default port:8888 or another number but when open browser port is changed in 8889 or another number+1
![atom](https://user-images.githubusercontent.com/36461382/36181083-8101756c-1123-11e8-8674-b91daf6d7809.jpg)

**Comment by leijou** [comment]
This means that port 8888 was already in use by another process and could not be used. Searching for the next available port is the expected behaviour
