### ISSUE TITLE
Package Depreciated?

### ISSUE THREAD

**Issue by theshka** [leijou/php-server#3]
I'm using Atom Version 0.208.0, and php-server 0.4.0 no longer loads. 

The error I see is `This package has not been loaded due to using depreciated APIs. There is no update available.` Did I break something? ;)

**Comment by nickbe** [comment]
Same here. I even tried to fix the problem but the php-server still won't load.
Could you please fix this guys :) ?

**Comment by theshka** [comment]
@AshIzat fixed the issue in PR #2, just waiting for it to be merged upstream. 

In the meantime, I just downloaded their version and manually installed with `apm install` :+1:

**Comment by ravecoyote** [comment]
I'm on windows 7 here.
I have no idea how to use apm, to install the package (I assume you can provide the .zip file somehow)...
All attems with apm.cmd install <package.tar> or <package-folder> result in an error: "Request for package information failed: not Found"

**Comment by theshka** [comment]
@ravecoyote I don't use Windows, so I'm not sure how much help I can be, but, try unzipping the package and moving it to `C:\Users\YOU\.atom\packages\php-server\`  then open a command line in the folder, and type `apm install` It sounds like Atom can't find the package.json file to install with.

**Comment by ravecoyote** [comment]
I already tried that. Ended up with a lot of errors.

**Comment by theshka** [comment]
This may be an issue with Atom, what version are you using? I found this thread, but there doesn't seem to be a solution yet: https://github.com/atom/settings-view/issues/514#issuecomment-104596802

**Comment by leijou** [comment]
Fixed by #2 in v0.5.0 Sorry for the wait
