### ISSUE TITLE
Dafualt port in the way

### ISSUE THREAD

**Issue by A-Scientist** [leijou/php-server#36]
I'm using XAMPP server on Windows 10 to run my php, but the default port is getting in the way. Using
http://localhost/scripts/PHP%20Practice.php
works but
http://localhost/scripts:8000/PHP%20Practice.php
, or with any port I've tried, does not. Unfortunately I can't find a way to stop it from putting a port number in, otherwise it just puts in the default. I'm a little new to this so that might be bad practice but it does work. Not sure if I can do anything to fix this myself.

**Comment by leijou** [comment]
This package uses PHP's built-in development server so it runs separately from apache or any other webserver.

You are using XAMPP to run apache and need to configure it to point to your development files, this package can't help with that.
