### ISSUE TITLE
Setting to disable opening in browser

### ISSUE THREAD

**Issue by bradynpoulsen** [leijou/php-server#7]
How do I disable the package from opening the started server in a URL. I use it often to test my APIs via Postman; however, I constantly have to close tab after tab that was opened by the plugin. Can we get an option to disable this feature?

**Comment by steave-r0gers** [comment]
Commit line 146
`open href`
in file ~/.atom/packages/php-server/lib/php-server.coffee

**Comment by leijou** [comment]
Added in v0.8.0 :+1:
